title: BePower
description: A brief wiki
url: "https://bepower.github.io"

permalink: pretty

exclude: ["README.md", "LICENSE", "Gemfile", "Gemfile.lock"]

remote_theme: just-the-docs/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: /assets/images/plenitude-becharge.svg

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# Aux links for the upper right navigation
aux_links:
  "BePower on GitHub":
    - "//github.com/BePower"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# External navigation links
nav_external_links:
  # - title: Just the Docs on GitHub
  #   url: https://github.com/just-the-docs/just-the-docs
  #   hide_icon: false # set to true to hide the external link icon - defaults to false

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
# gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme supports "light" (default) and "dark"
color_scheme: light

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-5555555-55
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

# Define Jekyll collections
# collections:
  # Define a collection named "roaming", its documents reside in the "_roaming" directory
  # roaming:
  #   permalink: "/:collection/:path/"
  #   output: true

# just_the_docs:
  # Define which collections are used in just-the-docs
  # collections:
    # Reference the "tests" collection
    # roaming:
      # Give the collection a name
      # name: Roaming
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true

plugins:
  - jekyll-seo-tag